# Generated by Django 3.2.6 on 2021-08-02 10:41

from django.db import migrations


def created_data(apps, schema_editor):
    Customer = apps.get_model('customer', 'Customer')
    Customer(first_name="Customer 001", last_name="Customer 001", email="customer001@email.com", phone="00000000")

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
    ]
